# Generated by Django 2.2.16 on 2021-12-13 21:34

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211213_2044'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='user and author can not be equal'),
        ),
    ]
