# Generated by Django 2.2.16 on 2021-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211213_2134'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='user can not subscribe twice'),
        ),
    ]
